"""Tests for ACL permissions in setup_openwrt_ha_integration.sh.

Verifies that the ACL JSON generated by the setup script contains all required
permissions for wired client detection (network.interface.dump, luci-rpc.getHostHints).
"""

import json
import os

SCRIPT_PATH = os.path.join(
    os.path.dirname(__file__),
    "..",
    "scripts",
    "setup_openwrt_ha_integration.sh",
)


def _extract_acl_json(dhcp_enabled: bool) -> dict:
    """Run the script's ACL generation logic and return parsed JSON.

    Uses bash to evaluate only the ACL-writing portion of the script with
    controlled DHCP_ENABLED and LUCI_RPC_PERMISSION variables, writing the
    result to a temp file instead of via SSH.
    """
    if dhcp_enabled:
        luci_rpc_permission = ',\n                "luci-rpc": [ "getDHCPLeases", "getHostHints" ]'
    else:
        luci_rpc_permission = ""

    # Read the script and extract the heredoc ACL template
    with open(SCRIPT_PATH) as f:
        script_content = f.read()

    # Extract just the cat heredoc block that writes the ACL JSON
    start = script_content.find("cat > /usr/share/rpcd/acl.d/hass.json << 'EOF'")
    end = script_content.find("EOF\n", start) + len("EOF\n")
    heredoc_block = script_content[start:end]

    # Replace the escaped quotes used inside SSH heredoc with regular JSON
    acl_template = heredoc_block
    acl_template = acl_template.replace("cat > /usr/share/rpcd/acl.d/hass.json << 'EOF'", "")
    acl_template = acl_template.replace("\nEOF\n", "")
    acl_template = acl_template.replace('\\"', '"')
    acl_template = acl_template.replace("$LUCI_RPC_PERMISSION", luci_rpc_permission)

    return json.loads(acl_template.strip())


def _get_read_ubus(acl: dict) -> dict:
    """Return the read.ubus block from parsed ACL."""
    return acl["hass"]["read"]["ubus"]


def _get_write_ubus(acl: dict) -> dict:
    """Return the write.ubus block from parsed ACL."""
    return acl["hass"]["write"]["ubus"]


class TestAclBasePermissions:
    """Tests for permissions present regardless of DHCP configuration."""

    def setup_method(self):
        self.acl_no_dhcp = _extract_acl_json(dhcp_enabled=False)
        self.acl_with_dhcp = _extract_acl_json(dhcp_enabled=True)

    def test_network_interface_dump_present_without_dhcp(self):
        ubus = _get_read_ubus(self.acl_no_dhcp)
        assert "network.interface" in ubus
        assert "dump" in ubus["network.interface"]

    def test_network_interface_dump_present_with_dhcp(self):
        ubus = _get_read_ubus(self.acl_with_dhcp)
        assert "network.interface" in ubus
        assert "dump" in ubus["network.interface"]

    def test_existing_permissions_preserved_without_dhcp(self):
        ubus = _get_read_ubus(self.acl_no_dhcp)
        assert "hostapd.*" in ubus
        assert "get_clients" in ubus["hostapd.*"]
        assert "iwinfo" in ubus
        assert "assoclist" in ubus["iwinfo"]
        assert "devices" in ubus["iwinfo"]
        assert "info" in ubus["iwinfo"]
        assert "system" in ubus
        assert "board" in ubus["system"]
        assert "info" in ubus["system"]
        assert "uci" in ubus
        assert "get" in ubus["uci"]
        assert "network.wireless" in ubus
        assert "status" in ubus["network.wireless"]
        assert "network.device" in ubus
        assert "status" in ubus["network.device"]
        assert "dhcp" in ubus
        assert "ipv4leases" in ubus["dhcp"]
        assert "ipv6leases" in ubus["dhcp"]

    def test_write_permissions_unchanged(self):
        for acl in (self.acl_no_dhcp, self.acl_with_dhcp):
            write_ubus = _get_write_ubus(acl)
            assert "session" in write_ubus
            assert "login" in write_ubus["session"]
            assert "access" in write_ubus["session"]
            assert "hostapd.*" in write_ubus
            assert "del_client" in write_ubus["hostapd.*"]


class TestAclDhcpPermissions:
    """Tests for DHCP-conditional permissions."""

    def setup_method(self):
        self.acl_with_dhcp = _extract_acl_json(dhcp_enabled=True)
        self.acl_no_dhcp = _extract_acl_json(dhcp_enabled=False)

    def test_luci_rpc_get_dhcp_leases_present_when_dhcp(self):
        ubus = _get_read_ubus(self.acl_with_dhcp)
        assert "luci-rpc" in ubus
        assert "getDHCPLeases" in ubus["luci-rpc"]

    def test_luci_rpc_get_host_hints_present_when_dhcp(self):
        ubus = _get_read_ubus(self.acl_with_dhcp)
        assert "luci-rpc" in ubus
        assert "getHostHints" in ubus["luci-rpc"]

    def test_luci_rpc_absent_when_no_dhcp(self):
        ubus = _get_read_ubus(self.acl_no_dhcp)
        assert "luci-rpc" not in ubus
